[phases.setup]
nixPkgs = ["python313", "python313Packages.pip"]

[phases.install]
cmds = [
    "python3 -m venv /app/.venv",
    "/app/.venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/app/.venv/bin/python -m app.migrate && /app/.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port $PORT"
